# -*- coding: utf-8 -*-
"""23051982_AngGeokEn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pvObLe5sxQvVVD5M-iJsM_2U96zy6IUm
"""

import streamlit as st
import transformers
from transformers import pipeline

def create_qa_bot():
    # Load the question-answering pipeline
    qa_pipeline = pipeline("question-answering", model='distilbert-base-cased-distilled-squad')

    return qa_pipeline

def ask_question(context, question, qa_pipeline):
    # Use the pipeline to answer the question based on the context
    result = qa_pipeline(context=context, question=question)

    return result['answer']

def main():
    # Create the question-answering bot
    qa_bot = create_qa_bot()

    # Example context and questions
    context = "Cursed Energy is the primary source of power for all sorcerers and living beings, it is a power source aligned with negative emotions used by sorcerers and cursed spirits to fuel their jujutsu. Negative emotions such as grief and anger are the foundation of cursed energy. These emotions exist to some degree within most humans and as a result, the vast majority of human beings possess cursed energy. If these negative emotions is higher than a certain degree, it grants the person the ability to see cursed spirits. These individuals are known as jujutsu sorcerers and they are very rare among the human race. Cursed energy leaks from the human body, accumulates, and ferments over time until a cursed spirit manifests. This is only the case with non-sorcerers, as sorcerers are trained to control and channel their cursed energy into jujutsu."

    st.title("About Cursed Energy")
    input_text = st.text_area("Question", value="Enter question here")
   
    
    # Ask questions and print answers
    if input_text == "Enter question here":
        st.markdown("A:")
    else:
        answer = ask_question(context, input_text, qa_bot)
        st.markdown(f"A: {answer}")

if __name__ == "__main__":
    main()




